name: Ubuntu 20.04
# INSPIRATION https://github.com/onqtam/doctest/pull/285/files/875052e18cf5f5f0b9176e59f847b6205f3efb78#

on:
  pull_request:
  push:
    branches:
      - master
#      - dev

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.linkage }}-${{ matrix.manager }}
    runs-on: ubuntu-20.04
    env:
      cache-name: cache-${{ matrix.compiler }}-${{ matrix.linkage }}-${{ matrix.manager }}
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   linkage: static, manager: cmake }
          - { compiler: gcc,   linkage: static, manager: conan }
          - { compiler: gcc,   linkage: static, manager: fetch }
          - { compiler: gcc,   linkage: static, manager: cpm }
          - { compiler: gcc,   linkage: static, manager: find  }
          - { compiler: gcc,   linkage: shared, manager: cmake }
          - { compiler: gcc,   linkage: shared, manager: conan }
          - { compiler: gcc,   linkage: shared, manager: fetch }
          - { compiler: gcc,   linkage: shared, manager: cpm }
          - { compiler: gcc,   linkage: shared, manager: find  }
          - { compiler: clang, linkage: static, manager: cmake }
          - { compiler: clang, linkage: static, manager: conan }
          - { compiler: clang, linkage: static, manager: fetch }
          - { compiler: clang, linkage: static, manager: cpm }
          - { compiler: clang, linkage: static, manager: find }
          - { compiler: clang, linkage: shared, manager: cmake }
          - { compiler: clang, linkage: shared, manager: conan }
          - { compiler: clang, linkage: shared, manager: fetch }
          - { compiler: clang, linkage: shared, manager: cpm }
          - { compiler: clang, linkage: shared, manager: find }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        if: contains(matrix.manager, 'conan')
        with:
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            ~/cpm-cache
#            ~/h5pp-install
#            build/Debug/h5pp-deps-install
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}
          max-size: 500M

      - name: Setup gcc # compilers are already installed on the CI
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get install gcc-10 g++-10 gfortran -y
          echo "FC=gfortran"  >> $GITHUB_ENV
          echo "CC=gcc-10"    >> $GITHUB_ENV
          echo "CXX=g++-10"   >> $GITHUB_ENV

      - name: Setup clang
        if: matrix.compiler == 'clang' # compilers are already installed on the CI # sudo apt-get install libclang-10-dev gfortran -y
        run: |
          echo "FC=gfortran"    >> $GITHUB_ENV
          echo "CC=clang-10"    >> $GITHUB_ENV
          echo "CXX=clang++-10" >> $GITHUB_ENV

      - name: Setup apt packages
        if: contains(matrix.manager,'find')
        run: sudo apt install libhdf5-dev libfmt-dev libspdlog-dev libeigen3-dev gcovr -y

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan user

      - name: Configure
        shell: bash
        run: |
          cmake -E make_directory build/Debug
          cd build/Debug
          cmake                                                       \
          -DCMAKE_BUILD_TYPE=Debug                                    \
          -DBUILD_SHARED_LIBS:BOOL=${{ matrix.linkage == 'shared' }}  \
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON                            \
          -DCMAKE_INSTALL_PREFIX:PATH=~/h5pp-install                  \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache                          \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache                        \
          -DH5PP_ENABLE_EIGEN3:BOOL=ON                                \
          -DH5PP_ENABLE_SPDLOG:BOOL=ON                                \
          -DH5PP_ENABLE_ASAN:BOOL=ON                                  \
          -DH5PP_ENABLE_TESTS:BOOL=ON                                 \
          -DH5PP_ENABLE_COVERAGE:BOOL=ON                              \
          -DH5PP_PACKAGE_MANAGER:STRING=${{ matrix.manager }}         \
          -DH5PP_PRINT_INFO:BOOL=ON                                   \
          -DH5PP_BUILD_EXAMPLES:BOOL=ON                               \
          -G "Unix Makefiles"                                         \
          ../../

      - name: Build
        run: |
          cd build/Debug
          cmake --build . --parallel 2

      - name: Install
        run: |
          cd build/Debug
          cmake --build . --target install

      - name: Test
        run: |
          cd build/Debug
          ctest -C Debug --output-on-failure -R h5pp

      - name: Coverage
        if: matrix.compiler == 'gcc' && matrix.linkage == 'static' && matrix.manager == 'find'
        run: |
          # Create lcov report
          lcov --capture --directory build/Debug --output-file coverage.info
          lcov --remove coverage.info '*/test-*' '/usr/*' '*include/fmt/*' '*include/spdlog/*' '*/Eigen/*' '*/hdf5/*' '*catch.hpp' --output-file coverage.info # filter system-files
          lcov --list coverage.info # debug info
          # Upload report to CodeCov
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"



